### PR TITLE
DEV-516/Remove custom callback_phase method

### PR DESCRIPTION
**Pull request by jrschnab**
| Related Stories
| ---------------
| [DEV-516](https://mobilize.atlassian.net/browse/DEV-516)

## Description, Motivation and Context

This redirect conditional is causing an open redirect security
vulnerability to occur by redirecting to the unchecked url parameter.
Removing this method in favor of utilizing the default omniauth-oauth2
callback_phase method.

This vulnerability is mitigated in the web-app by the omniauth/callback
url checks that occur on redirects.

Note that LinkedIn is not currently configured (for me at least) to test in dev, so once this and the gem update are in staging, we will need to validate 1) the LinkedIn login still works as expected and 2) the open redirect issue is resolved. 

Outstanding question for @dugancathal : because of the way we utilize this in our gemfile (https://github.com/mobilizeio/web-app/blob/99cc5defb1ba59d6e1900088a97927e11cf2f4ee/Gemfile#L46), once we push this change, it will be available to all environments. Is the best way to test this to wait to any builds and deploys to main until we've built and tested in dev?

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change, does not change functionality)
- [ ] Chore (non-breaking change, does not change functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires an Environment variable.

#### Development and Testing

- [x] The code change/moved as part of this PR has been covered with tests
- [x] All tests pass locally
- [ ] Considered Security, Availability and Confidentiality

#### Does this PR include a database migration?

- [x] No
- [ ] Yes
  - [ ] Verified backwards compatible
  - [ ] Verified database migrations will not be catastrophic 
  - [ ] Added the documentation to the `db/docs` directory
### For the Reviewer:

**By approving this PR, the reviewer acknowledges that they have checked all items in this done list.**

#### Reviewer/Approval Done List

- [ ] JIRA story has link to this pull request and this pull request has a link to the JIRA story(ies)
- [ ] Changes have been reviewed
- [ ] Reviewed impact to Security, Availability and Confidentiality (if issue found, add comments and request changes)
- [ ] Verified changes are backward compatible (only if database migration exists)

### CODE REVIEW

**Review by ejallday — APPROVED** [review]

**Comment by ejallday** [comment]
Will we need to bump the version of this? If we don't will the updated code be pulled in or will we be relying on a cached version?

**Comment by jrschnab** [comment]
@ejallday  that question feels pretty related to the outstanding question I posed to @dugancathal in the description. Since it points at a github repo rather than utilizing a version number, I'm not entirely sure how this would work (looking into it).

**Comment by jrschnab** [comment]
Looks like maybe adding a tag would be the best option? https://bundler.io/guides/git.html

**Review by dugancathal — APPROVED** [review]
I ... have no words. Excellent find.

**Comment by dugancathal** [comment]
@jrschnab Re: the deployment here. We'll need to do a `bundle update` in the web app and deploy that, but then, yes, there's no way to get the conditional behavior, so we'll block the deploy to prod until we've verified in staging.

For going forward until we can remove this, it would be a best practice to, as you said, lock the web-app Gemfile to a specific tag for the expected version.

**Pull request merged**
